CREATE DATABASE IF NOT EXISTS zhiqu_db
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'zhiqu_app'@'localhost'
  IDENTIFIED BY 'CHANGE_ME_DB_PASSWORD';

CREATE USER IF NOT EXISTS 'zhiqu_app'@'127.0.0.1'
  IDENTIFIED BY 'CHANGE_ME_DB_PASSWORD';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, DROP, REFERENCES,
      CREATE ROUTINE, ALTER ROUTINE, EXECUTE
ON zhiqu_db.* TO 'zhiqu_app'@'localhost';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, DROP, REFERENCES,
      CREATE ROUTINE, ALTER ROUTINE, EXECUTE
ON zhiqu_db.* TO 'zhiqu_app'@'127.0.0.1';

FLUSH PRIVILEGES;
